name: Update ESPN Soccer
on:
  schedule:
    - cron: '*/42 * * * *'
  workflow_dispatch:

jobs:
  scrape_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 lxml Pillow requests

      - name: Run ESPN Scraper
        run: python scraper_espn.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if [ -f espn.json ]; then
            git add espn.json
            git commit -m "Automated ESPN update" || exit 0
            
            for i in {1..3}; do
              git pull origin main --rebase
              if git push origin main; then
                echo "Uspješan push za ESPN!"
                exit 0
              fi
              echo "Pokušaj $i propao, čekam 5 sekundi..."
              sleep 5
            done
            exit 1
          else
            echo "Greška: espn.json nije pronađen!"
            exit 1
          fi
